name: deploy-to-EB

on:
  push:
    branches:
      - main
    
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: npm install
        working-directory: ./WEB(BE)
        run: npm install

      - name: npm compile with babel
        working-directory: ./WEB(BE)
        run: npm run compile
        
      - name: copy views to dist
        working-directory: ./WEB(BE)
        run: cp -r ./src/views ./dist

      - name: make zip file
        working-directory: ./WEB(BE)
        run: zip -r app.zip package.json ./dist

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: wilim-back
          environment_name: Wilimback-env
          version_label: ${{ github.run_number }}
          use_existing_version_if_available: true
          region: ap-northeast-2
          deployment_package: ./WEB(BE)/app.zip
